const classicIngredients = [
  "Flour",
  "Sugar",
  "Salt",
  "Butter",
  "Eggs",
  "Milk",
  "Baking Powder",
  "Vanilla Extract",
  "Cocoa Powder",
  "Vegetable Oil",
  "Yeast",
  "Honey",
  "Olive Oil",
  "Garlic",
  "Onion",
  "Tomato",
  "Potato",
  "Carrot",
  "Lettuce",
  "Cucumber",
  "Bell Pepper",
  "Chicken",
  "Beef",
  "Pork",
  "Fish",
  "Shrimp",
  "Rice",
  "Pasta",
  "Bread",
  "Cheese",
  "Mozzarella",
  "Parmesan",
  "Cheddar",
  "Gouda",
  "Swiss",
  "Blue Cheese",
  "Feta",
  "Brie",
  "Camembert",
  "Goat Cheese",
  "Havarti",
  "Mayonnaise",
  "Mustard",
  "Ketchup",
  "Soy Sauce",
  "Vinegar",
  "Lemon Juice",
  "Oregano",
  "Basil",
  "Thyme",
  "Rosemary",
  "Cinnamon",
  "Nutmeg",
  "Ginger",
  "Paprika",
  "Chili Powder",
  "Black Pepper",
  "Salt",
  "Brown Sugar",
  "White Sugar",
  "Powdered Sugar",
  "Honey",
  "Maple Syrup",
  "Chocolate Chips",
  "Nuts",
  "Oats",
  "Coconut",
  "Raisins",
  "Almond Extract",
  "Coconut Milk",
  "Sour Cream",
  "Greek Yogurt",
  "Whipped Cream",
  "Ice Cream",
  "Chocolate Sauce",
  "Caramel Sauce",
  "Peanut Butter",
  "Jam",
  "Nutella",
  "Marshmallows",
  "Sprinkles",
  "Food Coloring",
  "Baking Soda",
  "Cornstarch",
  "Gelatin",
  "Cornmeal",
  "Panko Breadcrumbs",
  "Crackers",
  "Biscuits",
  "Tortillas",
  "Salsa",
  "Guacamole",
  "Sour Cream",
  "Salsa",
  "Hummus",
  "Tahini",
  "Pita Bread",
  "Naan Bread",
  "Baguette",
  "Croissant",
  "Donut",
  "Muffin",
  "Cake",
  "Pie",
  "Cookies",
  "Brownies",
  "Pancakes",
  "Waffles",
  "Crepes",
  "Pizza Dough",
  "Burger Buns",
  "Hot Dog Buns",
  "Sandwich Bread",
  "Taco Shells",
  "Burrito Wraps",
  "Sushi Rice",
  "Nori Sheets",
  "Sesame Seeds",
  "Soy Milk",
  "Almond Milk",
  "Coconut Water",
  "Green Tea",
  "Coffee",
  "Juice",
  "Water",
];
export default classicIngredients;
